name = "youtube"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "LINK"
id = "0528c741f1d845699ee4a9ebb2886839"
preview_id = "0528c741f1d845699ee4a9ebb2886839"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"